import Head from 'next/head';
import Body from '../components/Body';
import Footer from '../components/Footer';
import Header from '../components/Header';

export default function Home() {
  return (
    <div className>
      <Head>
        <title>Google v3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <Header />

      {/* BODY */}
      <Body />

      {/* FOOTER */}
      <Footer />
    </div>
  );
}
